micronaut:
  application:
    name: kustomize
  http:
    client:
      read-timeout: 30s
logger:
  levels:
    ROOT: OFF
    io.micronaut.http.client.netty.DefaultHttpClient: OFF # TRACE to see http requests and responses


